#!/bin/bash

mkdir ~/ratiocontour -p
unzip code.zip -d ~/ratiocontour
unzip MCRInstaller.zip -d ~/ratiocontour
cp setBASH ~/ratiocontour
cp setCSH ~/ratiocontour
cp README ~/ratiocontour
cp pami05.pdf ~/ratiocontour
cp -r images ~/ratiocontour

#restore links
cd ~/ratiocontour/v73/bin/glnx86
ln -s libhdf5.so.0.0.0 libhdf5.so.0
ln -s libicudata.so.32.0 libicudata.so.32
ln -s libicudata.so.32 libicudata.so
ln -s libicui18n.so.32.0 libicui18n.so.32
ln -s libicui18n.so.32 libicui18n.so
ln -s libicuio.so.32.0 libicuio.so.32
ln -s libicuio.so.32 libicuio.so
ln -s libicuuc.so.32.0 libicuuc.so.32
ln -s libicuuc.so.32 libicuuc.so
ln -s libtiff.so.3.7.1 libtiff.so.3
ln -s libtiff.so.3 libtiff.so
ln -s libxerces-c.so.26.0 libxerces-c.so.26
ln -s libxerces-c.so.26 libxerces-c.so
ln -s libz.so.1.1.4 libz.so.1
ln -s libz.so.1 libz.so
mkdir ~/ratiocontour/v73/sys/java/jre/glnx86/jre1.5.0/javaws -p
cd ~/ratiocontour/v73/sys/java/jre/glnx86/jre1.5.0/javaws
ln -s ../bin/javaws
cd ~/ratiocontour/v73/sys/java/jre/glnx86/jre1.5.0/lib/i386/client
ln -s ../libjsig.so
cd ~/ratiocontour/v73/sys/java/jre/glnx86/jre1.5.0/lib/i386/server
ln -s ../libjsig.so
cd ~/ratiocontour/v73/sys/opengl/lib/glnx86
ln -s libGL.so.1.5.060001 libGL.so
ln -s libGLU.so.1.3.060001 libGLU.so
ln -s libGL.so.1.5.060001 libMesaGL.so
ln -s libGLU.so.1.3.060001 libMesaGLU.so
cd ~/ratiocontour/v73/sys/os/glnx86
ln -s libg2c.so.0.0.0 libg2c.so.0
ln -s libstdc++.so.5.0.3 libstdc++.so.5

