#!/bin/csh

set MCRPATH=~/ratiocontour/v73
 
setenv LD_LIBRARY_PATH $MCRPATH/runtime/glnx86:$MCRPATH/sys/os/glnx86:$MCRPATH/sys/java/jre/glnx86/jre1.5.0/lib/i386/native_threads:$MCRPATH/sys/java/jre/glnx86/jre1.5.0/lib/i386/client:$MCRPATH/sys/java/jre/glnx86/jre1.5.0/lib/i386:$MCRPATH/bin/glnx86

setenv XAPPLRESDIR $MCRPATH/X11/app-defaults


